name: Publish package

on:
  push:
    tags: ["*"]

permissions:
  contents: read
  id-token: write

jobs:
  pypi:
    uses: tree-sitter/workflows/.github/workflows/package-pypi.yml@main
    secrets:
      PYPI_API_TOKEN: ${{secrets.PYPI_API_TOKEN}}
    with:
      package-name: tree-sitter-apache-avro-unofficial
      generate: true
